base_url = "https://ansharora28.github.io/hackerspaces.in"
title = "Hackerspaces in India"
description = "Directory of Hackerspaces across India"
compile_sass = false
minify_html = true

[markdown]

[[taxonomies]]
name = "states"
feed = false

[[taxonomies]]
name = "cities"
feed = false

[[taxonomies]]
name = "categories"
feed = false
